using System;
using System.Reflection;
using GLib;
using HarmonyLib;
using Lopital;
using UnityEngine.UI;

namespace HospitalPorters
{
    internal static class PorterCustomHiringState
    {
        internal static int CreationDepth;
    }

    [HarmonyPatch(typeof(CharacterEditorController), "RandomizeCharacter", new Type[] { typeof(string) })]
    internal static class PorterCustomHiringCharacterCreationPatch
    {
        [HarmonyPrefix]
        [HarmonyPriority(Priority.First)]
        private static void Prefix()
        {
            if (!PorterHiringState.Active ||
                HiringManager.Instance == null ||
                HiringManager.Instance.m_workspace == null ||
                !PorterHiringUi.IsPorterWorkspace(HiringManager.Instance.m_workspace))
            {
                return;
            }

            PorterCustomHiringState.CreationDepth++;
        }

        [HarmonyPostfix]
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(CharacterEditorController __instance)
        {
            PorterCustomHiringPresentationPatch.Apply(__instance);
        }

        [HarmonyFinalizer]
        [HarmonyPriority(Priority.Last)]
        private static Exception Finalizer(Exception __exception)
        {
            if (PorterCustomHiringState.CreationDepth > 0)
            {
                PorterCustomHiringState.CreationDepth--;
            }

            return __exception;
        }
    }

    [HarmonyPatch(
        typeof(LopitalEntityFactory),
        nameof(LopitalEntityFactory.CreateCharacterNurse),
        new Type[]
        {
            typeof(Floor), typeof(Vector2i), typeof(int), typeof(int), typeof(GameDBSkill), typeof(string)
        })]
    internal static class PorterCustomHiringNurseFactoryPatch
    {
        [HarmonyPostfix]
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(Entity __result)
        {
            if (PorterCustomHiringState.CreationDepth <= 0 ||
                __result == null ||
                PorterIdentity.IsPorter(__result))
            {
                return;
            }

            if (!PorterIdentity.SetPorterOccupation(__result))
            {
                Plugin.Log?.LogError(
                    "Custom Porter creation failed to convert the CharacterNurse generated by CharacterEditorController.");
            }
        }
    }

    [HarmonyPatch(typeof(CharacterEditorController), "FillCharacterData")]
    internal static class PorterCustomHiringPresentationPatch
    {
        private const int NativeNurseOccupationIcon = 370;
        private const int NativeNurseOccupationInactiveIcon = 0;
        private const string NativeNurseOccupationTooltip = "OCCUPATION_NURSE";
        private const int NativeCharacterLevelMinFontSize = 14;
        private const int PorterCharacterLevelMinFontSize = 8;

        private static readonly FieldInfo CharacterField =
            AccessTools.Field(typeof(CharacterEditorController), "m_character");

        private static readonly PropertyInfo ResizeTextMinSizeProperty =
            AccessTools.Property(typeof(Text), "resizeTextMinSize");

        [HarmonyPostfix]
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(CharacterEditorController __instance)
        {
            Apply(__instance);
        }

        internal static void Apply(CharacterEditorController __instance)
        {
            if (__instance == null)
            {
                return;
            }

            RestoreNativeCharacterLevelText(__instance);

            Entity character =
                object.ReferenceEquals(CharacterField, null)
                    ? null
                    : CharacterField.GetValue(__instance) as Entity;
            if (character == null || character.GetComponent<BehaviorNurse>() == null)
            {
                return;
            }

            IconButtonController occupationButton =
                __instance.m_nurseOccupationIcon == null
                    ? null
                    : __instance.m_nurseOccupationIcon.GetComponent<IconButtonController>();

            if (!PorterIdentity.IsPorter(character))
            {
                if (occupationButton != null &&
                    occupationButton.m_toolTipTextLocalizationID == PorterIds.Occupation)
                {
                    occupationButton.SetIcon(NativeNurseOccupationIcon);
                    occupationButton.SetInactiveIcon(NativeNurseOccupationInactiveIcon);
                    occupationButton.SetTextLocID(NativeNurseOccupationTooltip);
                }
                return;
            }

            EmployeeComponent employee = character.GetComponent<EmployeeComponent>();
            if (employee != null && __instance.m_occupationText != null)
            {
                Text occupationText = __instance.m_occupationText.GetComponent<Text>();
                if (occupationText != null)
                {
                    SetCharacterLevelMinFontSize(
                        occupationText,
                        PorterCharacterLevelMinFontSize);
                    occupationText.text = LocalizationManager.Get(
                        PorterIds.GetPorterLevelLocalizationId(
                            employee.m_state.m_level));
                }
            }

            if (occupationButton != null)
            {
                PorterVisuals.ApplyCategoryIcons(occupationButton);
                occupationButton.SetTextLocID(PorterIds.Occupation);
            }
        }

        private static void RestoreNativeCharacterLevelText(
            CharacterEditorController instance)
        {
            if (instance == null || instance.m_occupationText == null)
            {
                return;
            }

            Text levelText = instance.m_occupationText.GetComponent<Text>();
            if (levelText != null)
            {
                SetCharacterLevelMinFontSize(
                    levelText,
                    NativeCharacterLevelMinFontSize);
            }
        }

        private static void SetCharacterLevelMinFontSize(
            Text text,
            int minFontSize)
        {
            if (text == null || ResizeTextMinSizeProperty == null)
            {
                return;
            }

            ResizeTextMinSizeProperty.SetValue(
                text,
                minFontSize,
                null);
        }
    }

}
